# This file is a mapping between the old and new names of config

mapping = {'DEFAULT_DAE': 'Collada (.dae)',
           'DEFAULT_ABC': 'Alembic (.abc)',
           'DEFAULT_USD': 'USD (.usd/.usda/.usdc)',
           'DEFAULT_SVG': 'SVG (.svg)',
           'DEFAULT_PLY': 'Stanford (.ply)',
           'DEFAULT_STL': 'Stl (.stl)',
           'DEFAULT_FBX': 'FBX (.fbx)',
           'DEFAULT_GLTF': 'glTF 2.0 (.gltf/.glb)',
           'DEFAULT_OBJ': 'Wavefront (.obj)',
           'DEFAULT_X3D': 'X3D (.x3d/.wrl)',
           'EXPORT_DAE': 'Collada (.dae)',
           'EXPORT_ABC': 'Alembic (.abc)',
           'EXPORT_USD': 'USD (.usd)',
           'EXPORT_USDC': 'USD (.usdc)',
           'EXPORT_USDA': 'USD (.usda)',
           'EXPORT_PLY': 'Stanford (.ply)',
           'EXPORT_STL': 'Stl (.stl)',
           'EXPORT_FBX': 'FBX (.fbx)',
           'EXPORT_GLTF': 'glTF 2.0 (.gltf)',
           'EXPORT_OBJ': 'Wavefront (.obj)',
           'EXPORT_SVG': 'Grease Pencil (.svg)',
           'EXPORT_BLEND': 'Blend (.blend)',
           'APPEND_BLEND_MATERIAL': 'Append All Materials',
           'APPEND_BLEND_COLLECTION': 'Append All Collections',
           'APPEND_BLEND_OBJECT': 'Append All Objects',
           'APPEND_BLEND_WORLD': 'Append All Worlds',
           'APPEND_BLEND_NODETREE': 'Append All Node Groups',
           'LINK_BLEND_MAT': 'Link All Materials',
           'LINK_BLEND_COLLECTION': 'Link All Collections',
           'LINK_BLEND_OBJECT': 'Link All Objects',
           'LINK_BLEND_WORLD': 'Link All Worlds',
           'LINK_BLEND_NODE': 'Link All Node Groups',
           'ADDONS_BLEND_MATERIAL': 'Append and Assign Material',
           'ADDONS_BLEND_WORLD': 'Append and Assign world',
           'ADDONS_INSTALL_ADDON': 'Install Addon (.py/.zip)',
           'ADDONS_IMPORT_IES': 'Import IES (.ies)',
           'ADDONS_IMPORT_PBR_ZIP': 'Import PBR Material (.zip)',
           'CUSTOM': 'Custom'}
